### ISSUE TITLE
Support scaling of images

### ISSUE THREAD

**Issue by sailtake5** [delighted/sketch-scale-all-in-place#3]
This is not working - the dialogue box to select a percentage to resize is not coming up when I choose the plugin from the menu.

**Comment by mikegee0101** [comment]
@sailtake5 What version of Sketch are you running? Do you have at least 2 shapes selected?

**Comment by sailtake5** [comment]
I'm trying to resize logos (.png) that are all the same size.

**Comment by mikegee0101** [comment]
@sailtake5 Ah ok. The plugin doesn't currently support scaling images. I can look into supporting it.

**Comment by mikegee0101** [comment]
Images should work in the latest version. Let me know if you have any issues.
