### ISSUE TITLE
Percentage dialogue doesn't open

### ISSUE THREAD

**Issue by JoshN-2018** [delighted/sketch-scale-all-in-place#8]
I'm using sketch 49.3 (latest version at time of writing) Unfortunately the percentage dialogue box doesn't open when the plugin is run. It seems other aspects are working as theres an option to run the plugin again. But without the dialogue box the core functionality is broken. This is an amazing feature and very big oversight by Bohemian coding. Thank you for taking the time to make this plugin and make sketch a much more complete package. Hopefully its a quick fix!

thanks again!

**Comment by mikegee0101** [comment]
Should work in latest release. Let me know if you see anymore issues.
